set nocompatible

set backspace=indent,eol,start
set autoindent

set expandtab
set tabstop=4
set shiftwidth=4

set fileformats=dos,unix

set backup
set backupdir=~/.vim/backup//
set directory=~/.vim/swap//
let myvar = strftime("%y%m%dT%H%M")
let myvar = "set backupext=-".myvar
execute myvar
